# include=~/.config/fuzzel/themes/noctalia

[main]
# prompt = "hello"
font = Maple Mono NF CN:size=16
width = 60
lines = 18
match-mode = fzf
show-actions = no

[border]
width = 0
radius = 8
selection-radius = 4

[colors]
background=191724CC
text=ffffffff
prompt=9ccfd8ff
placeholder=31748fff
input=ebbcbaff
match=31748fff
selection=ebbcba80
selection-text=ffffffff
selection-match=000000ff
counter=9ccfd8ff
border=ebbcbaff
