# Wayland & XWayland Environment for Niri
# This file is read by systemd --user on login, ensuring variables 
# are available to D-Bus services and all user applications.

# ---------------------------------------------------------
# wayland 协议& 窗口管理器 & 桌面环境配置
# ---------------------------------------------------------
ELECTRON_OZONE_PLATFORM_HINT=auto
QT_QPA_PLATFORM="wayland;xcb"
# QT_QPA_PLATFORM=wayland
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
QT_AUTO_SCREEN_SCALE_FACTOR=1
XDG_SESSION_TYPE=wayland
#应用图标显示问题
QT_QPA_PLATFORMTHEME=gtk3
# QT_QPA_PLATFORMTHEME=qt5ct
# XDG_CURRENT_DESKTOP=niri:GNOME
# 由 ~/.config/systemd/user/xdg-desktop-portal.service.d/override.conf 配置
# XDG_CURRENT_DESKTOP=niri
# XDG_DESKTOP_PORTAL=xdg-desktop-portal-gtk
# 禁止这样配置，会导致[录屏/屏幕]共享失效
#GDK_BACKEND="wayland,x11"
GDK_BACKEND=wayland
XDG_SESSION_DESKTOP=niri

# ---------------------------------------------------------
# wayland 下 fcitx5 中文输入法
# ---------------------------------------------------------
XMODIFIERS=@im=fcitx
# 必须配置，否则某些 QT 程序不能输入中文
QT_IM_MODULE=fcitx
# QT 6.7+ 新增配置，按顺序加载
QT_IM_MODULES="wayland;fcitx;ibus"
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=ibus

# ---------------------------------------------------------
# 声音驱动配置，强烈推荐使用 pipewire
# ---------------------------------------------------------
SDL_AUDIODRIVER=pipewire

# ---------------------------------------------------------
# firefox wayland 配置
# ---------------------------------------------------------
MOZ_ENABLE_WAYLAND=1
MOZ_USE_XINPUT=1
MOZ_DISABLE_RDD_SANDBOX=1

# ---------------------------------------------------------
# 通过环境变量强制XWayland应用使用特定缩放行为
# ---------------------------------------------------------
# GDK_SCALE=1          # 整数倍缩放（如200%）
# GDK_DPI_SCALE=1    # 微调DPI缩放（与GDK_SCALE互为倒数）
# SUN_JAVA2D_UI_SCALE=1 # 直接缩放Java 2D渲染（部分应用有效）
# 基于 JAVA Swing/AWT 应用在窗口管理器下 “缩放模糊或界面错位问题”
_JAVA_AWT_WM_NONREPARENTING=1
